additional_eval_descs:
  - dogs;cats;bananas;
  - 7@9.qwepra#/.sd,s'2OC^039u#rdagjbL
  - ggggggggggggggggggggg
batch_size: 8
train_ds_names:
  - cul_China
  - cul_Germany
  - cul_India
  - cul_Japan
  - cul_Mexico 
  - cul_Southafrica
  - cul_UK
  - cul_Argentina
  - cul_Egypt
  - cul_France
  - cul_Italy
  - cul_Russia
  - cul_Turkey
  - cul_US
epochs: 10
eval_ds_info:
  cul_China: None
  cul_Germany: None
  cul_India: None
  cul_Japan: None
  cul_Mexico: None
  cul_Southafrica: None
  cul_UK: None
  cul_Argentina: None
  cul_Egypt: None
  cul_France: None
  cul_Italy: None
  cul_Russia:  None
  cul_Turkey: None
  cul_US: None
exp_setup: hyper_lora
grad_accum_steps: 64 # ?
logging_freq: 10%
val_freq: 10%
# gen_freq: 10000000
lr: 0.00001
max_grad_norm: 1.0
model_dir: models/Llama-3.1-8B-Instruct/
neftune_noise_alpha: 5
seed: 42
skip_eval: false
target_modules:
  - q_proj
  - v_proj
sft_mode: completion
use_one_hot_task_emb: true
use_per_task_emb: true
warmup_frac: 0.1
use_hierarchical_sampler: true
ds_type: align
n_train_ds: 2
n_ds_per_batch: 8 # number of datasets per batch
